import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import '../../design-system/styles.css';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// Register the Vite PWA service worker (generated by vite-plugin-pwa).
// This import is injected by the plugin at build time; in dev it is a no-op.
if ('serviceWorker' in navigator) {
  import('virtual:pwa-register').then(({ registerSW }) => {
    registerSW({ immediate: false });
  }).catch(() => {
    // virtual:pwa-register is absent in non-PWA dev builds — ignore.
  });
}
